################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "http://conholdate.app"
theme = "conholdate-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []

################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]

################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

################################# Default parameters ##########################
[params]
logo = "https://cms.admin.containerize.com/templates/conholdate/img/svg/conholdate-logo.svg"
logo_width = "270px"
# OpenGraph / Twitter Card metadata
description = "Enable your applications to manipulate Word, Excel, PDF, PowerPoint, Outlook and more than 100 other file formats for all major platforms."
author = "Conholdate"
# this image will be used as fallback if a page has no image of its own
image = "https://cms.admin.containerize.com/templates/conholdate/img/svg/conholdate-logo.svg"

################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2

################################# Translations #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

[languages.ru]
languageName = "Русский"
languageCode = "ru-RU"
contentDir = "content/russian"
weight = 2